# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('home', '0006_auto_20160918_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileList',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('profiles', wagtail.wagtailcore.fields.StreamField((('profile', wagtail.wagtailcore.blocks.StructBlock((('fullname', wagtail.wagtailcore.blocks.CharBlock(required=True, unique=True)), ('society_role', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('biography', wagtail.wagtailcore.blocks.RichTextBlock(required=True)), ('male', wagtail.wagtailcore.blocks.BooleanBlock(required=True)), ('photo', wagtail.wagtailimages.blocks.ImageChooserBlock())))),))),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='main_news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.NewsArticle'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='main_past_event_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='main_past_event_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='med_news_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.NewsArticle'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='med_past_event_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='med_past_event_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='small_future_event_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='small_future_event_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='small_future_event_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='small_news_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.NewsArticle'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='small_news_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.NewsArticle'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='small_news_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.NewsArticle'),
        ),
    ]
