# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('home', '0007_auto_20160918_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock())))),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='profilelist',
            name='profiles',
            field=wagtail.wagtailcore.fields.StreamField((('profile', wagtail.wagtailcore.blocks.StructBlock((('fullname', wagtail.wagtailcore.blocks.CharBlock(required=True, unique=True)), ('committee_role', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('biography', wagtail.wagtailcore.blocks.RichTextBlock(required=True)), ('sex', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')])), ('photo', wagtail.wagtailimages.blocks.ImageChooserBlock())))),)),
        ),
    ]
