# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 00:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_eventspage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='main_past_event_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.EventsPage'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='main_past_event_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.EventsPage'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='med_past_event_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.EventsPage'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='med_past_event_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.EventsPage'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='small_future_event_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.EventsPage'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='small_future_event_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.EventsPage'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='small_future_event_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.EventsPage'),
        ),
    ]
