# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('home', '0012_auto_20160919_0141'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventList',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('events', wagtail.wagtailcore.fields.StreamField((('event', wagtail.wagtailcore.blocks.StructBlock((('start', wagtail.wagtailcore.blocks.DateTimeBlock()), ('end', wagtail.wagtailcore.blocks.DateTimeBlock()), ('name', wagtail.wagtailcore.blocks.CharBlock()), ('description', wagtail.wagtailcore.blocks.CharBlock()), ('location', wagtail.wagtailcore.blocks.CharBlock())))),))),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='eventspage',
            name='page_ptr',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='main_past_event_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.NewsArticle'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='main_past_event_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.NewsArticle'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='med_past_event_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.NewsArticle'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='med_past_event_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.NewsArticle'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='small_future_event_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.NewsArticle'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='small_future_event_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.NewsArticle'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='small_future_event_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.NewsArticle'),
        ),
        migrations.DeleteModel(
            name='EventsPage',
        ),
    ]
